name: Unit Tests
on:
  [pull_request ]

jobs:
  test:  
    runs-on: ubuntu-latest.
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm    
    - uses: actions/download-artifact@v2
      with:
        name: assets
        path: dist
    - name: Run Tests
      run: npm test